services:
  mongodb:
    image: mongo:latest
    container_name: shoppinglistdb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  hrp-api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    container_name: hrp-api
    restart: always
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongodb:27017/shoppinglistdb
      - MQTT_BROKER=wss://mqtt.zimolong.eu
      - MQTT_USERNAME=dhbw
      - MQTT_PASSWORD=dhbw
      - MQTT_TOPIC=WWI23B2/kroeger
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start

  mqtt-subscriber:
    build:
      context: ./
      dockerfile: Dockerfile.subscriber
    container_name: mqtt-subscriber
    restart: always
    depends_on:
      - mongodb
    environment:
      - MQTT_BROKER=wss://mqtt.zimolong.eu
      - MQTT_USERNAME=dhbw
      - MQTT_PASSWORD=dhbw
      - MQTT_TOPIC=WWI23B2/kroeger
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run mqtt

volumes:
  mongo_data: